### ISSUE TITLE
'./xcbnotif' terminated by signal SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by CamilleScholtz** [lucas8/notification#1]
See title, here is the gdb log:

```
Starting program: /home/onodera/code/git/notification/xcbnotif 

Program received signal SIGSEGV, Segmentation fault.
0x00000000004039f6 in add_gc (name=0x607230 "urgent", c=0x607580, 
    scr=0x607160) at graphic.c:186
186     ctx->gc.font_height = reply->font_ascent + reply->font_descent;
```

Seems to be fixed by setting a `global.gc.font`, there is however no mention of this option in the README.

**Comment by dwarfmaster** [comment]
You are right, I forgot to mention the possibility to specify a font, I will add it to the README. When the font is not specified, it uses a harcoded font. My guess is that you don't have this font installed : 

```
-*-terminal-medium-r-*-*-14-*-*-*-*-*-iso8859-*
```

When loading the defaults values, the program does not check if an error happened, resulting in the segfault you encontered. I will add a warning about that in the README.

**Comment by dwarfmaster** [comment]
Done with commit b5bf867
I will not fix the segfault for now as it would need refactoring the code to add a better error-propagation system, and I don't have the time to do it now.

**Comment by dwarfmaster** [comment]
Should not segfault anymore (but the error message is not really explicit) : 33b8b93
